
package publicadores;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ControladorPublish", targetNamespace = "http://publicadores/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ControladorPublish {


    /**
     * 
     * @return
     *     returns publicadores.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ControladorPublish/listarLectoresSuspendidosRequest", output = "http://publicadores/ControladorPublish/listarLectoresSuspendidosResponse")
    public StringArray listarLectoresSuspendidos();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/ControladorPublish/cambiarZonaRequest", output = "http://publicadores/ControladorPublish/cambiarZonaResponse")
    public void cambiarZona(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/ControladorPublish/suspenderUsuarioRequest", output = "http://publicadores/ControladorPublish/suspenderUsuarioResponse")
    public void suspenderUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns publicadores.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ControladorPublish/listarLectoresRequest", output = "http://publicadores/ControladorPublish/listarLectoresResponse")
    public StringArray listarLectores();

    /**
     * 
     * @return
     *     returns publicadores.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ControladorPublish/listarBibliotecariosRequest", output = "http://publicadores/ControladorPublish/listarBibliotecariosResponse")
    public StringArray listarBibliotecarios();

    /**
     * 
     * @return
     *     returns publicadores.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ControladorPublish/obtenerMaterialesConPrestamosPendientesRequest", output = "http://publicadores/ControladorPublish/obtenerMaterialesConPrestamosPendientesResponse")
    public StringArray obtenerMaterialesConPrestamosPendientes();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns publicadores.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ControladorPublish/obtenerMaterialesPorRangoFechasRequest", output = "http://publicadores/ControladorPublish/obtenerMaterialesPorRangoFechasResponse")
    public StringArray obtenerMaterialesPorRangoFechas(
        @WebParam(name = "arg0", partName = "arg0")
        DtFecha arg0,
        @WebParam(name = "arg1", partName = "arg1")
        DtFecha arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/ControladorPublish/agregarLibroRequest", output = "http://publicadores/ControladorPublish/agregarLibroResponse")
    public void agregarLibro(
        @WebParam(name = "arg0", partName = "arg0")
        DtLibro arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/ControladorPublish/agregarArticuloRequest", output = "http://publicadores/ControladorPublish/agregarArticuloResponse")
    public void agregarArticulo(
        @WebParam(name = "arg0", partName = "arg0")
        DtArticulo arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/ControladorPublish/agregarPrestamoRequest", output = "http://publicadores/ControladorPublish/agregarPrestamoResponse")
    public void agregarPrestamo(
        @WebParam(name = "arg0", partName = "arg0")
        DtPrestamo arg0);

    /**
     * 
     * @return
     *     returns publicadores.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ControladorPublish/listarMaterialesRequest", output = "http://publicadores/ControladorPublish/listarMaterialesResponse")
    public StringArray listarMateriales();

    /**
     * 
     * @return
     *     returns publicadores.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ControladorPublish/listarIdsMaterialesRequest", output = "http://publicadores/ControladorPublish/listarIdsMaterialesResponse")
    public StringArray listarIdsMateriales();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/ControladorPublish/agregarBibliotecarioRequest", output = "http://publicadores/ControladorPublish/agregarBibliotecarioResponse")
    public void agregarBibliotecario(
        @WebParam(name = "arg0", partName = "arg0")
        DtBibliotecario arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://publicadores/ControladorPublish/agregarLectorRequest", output = "http://publicadores/ControladorPublish/agregarLectorResponse")
    public void agregarLector(
        @WebParam(name = "arg0", partName = "arg0")
        DtLector arg0);

    /**
     * 
     * @return
     *     returns publicadores.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://publicadores/ControladorPublish/obtenerTodasLasZonasRequest", output = "http://publicadores/ControladorPublish/obtenerTodasLasZonasResponse")
    public StringArray obtenerTodasLasZonas();

}
